#!/bin/sh
#
# PROVIDE: mchurl
# REQUIRE: networking
# KEYWORD:

. /etc/rc.subr

name="mchurl"
rcvar="mchurl_enable"
mchurl_user="mchurl"
mchurl_command="/usr/local/mchurl/mchurl"
pidfile="/var/run/mchurl/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f ${mchurl_command}"

load_rc_config $name
: ${mchurl_enable:=no}

run_rc_command "$1"