export { configureFakeBackend } from './fakeBackend'
export { handleResponse } from './handleResponse'
export { authHeader } from './authHeader'
export { history } from './history'
export { parseJwt } from './parseJwt'
export { default as canUseDom } from './canUseDom'